
let currentCountry = localStorage.getItem('trad_eu_v3_country') || COUNTRIES[0];
let reviews = JSON.parse(localStorage.getItem('trad_eu_v3_reviews') || '{}');
let locks = JSON.parse(localStorage.getItem('trad_eu_v3_locks') || '{}');
const app = document.getElementById('app');
function html(s){return String(s||'').replace(/[&<>"']/g,function(m){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m];});}
function byCountry(c){return TRADITIONS.filter(function(t){return t.country===c;});}
function statusOf(t){return reviews[t.id]&&reviews[t.id].status?reviews[t.id].status:'À valider';}
function commentOf(t){return reviews[t.id]&&reviews[t.id].comment?reviews[t.id].comment:'';}
function save(){localStorage.setItem('trad_eu_v3_reviews',JSON.stringify(reviews));localStorage.setItem('trad_eu_v3_locks',JSON.stringify(locks));localStorage.setItem('trad_eu_v3_country',currentCountry);}
function counts(){let c={OK:0,'À reformuler':0,'À remplacer':0,Doublon:0,'À valider':0};TRADITIONS.forEach(function(t){let s=statusOf(t);c[s]=(c[s]||0)+1;});return c;}
function countryStatus(c){if(locks[c])return'done';let st=byCountry(c).map(statusOf);if(st.some(function(s){return s==='À remplacer'||s==='Doublon';}))return'problem';if(st.some(function(s){return s==='À reformuler';}))return'review';if(st.every(function(s){return s==='OK';}))return'done';return'';}
function progressCountry(c){let arr=byCountry(c);let done=arr.filter(function(t){return statusOf(t)!=='À valider';}).length;return Math.round(done/arr.length*100);}
function renderTrad(t){let locked=!!locks[t.country];let out='';out+='<div class="card '+(locked?'locked':'')+'">';out+='<div><span class="pill">'+html(t.id)+'</span><span class="pill">'+html(t.theme)+'</span><span class="pill">Statut : '+html(statusOf(t))+'</span></div>';out+='<h3 class="trad-title">'+html(t.name)+'</h3>';out+='<div class="description">'+html(t.description)+'</div>';out+='<div class="question">'+html(t.question)+'</div>';out+='<div class="answers">';t.answers.forEach(function(a,i){out+='<div class="answer '+(a===t.correct?'correct':'')+'">'+String.fromCharCode(65+i)+'. '+html(a)+'</div>';});out+='</div>';out+='<div class="explanation"><strong>Bonne réponse :</strong> '+html(t.correct)+'<br><br><strong>Explication :</strong> '+html(t.explanation)+'</div>';out+='<h4>Commentaire</h4><textarea class="comment" id="comment_'+html(t.id)+'" '+(locked?'disabled':'')+'>'+html(commentOf(t))+'</textarea>';out+='<div class="actions"><button class="btn ok" onclick="setStatus(\''+t.id+'\',\'OK\')" '+(locked?'disabled':'')+'>OK</button><button class="btn rewrite" onclick="setStatus(\''+t.id+'\',\'À reformuler\')" '+(locked?'disabled':'')+'>À reformuler</button><button class="btn replace" onclick="setStatus(\''+t.id+'\',\'À remplacer\')" '+(locked?'disabled':'')+'>À remplacer</button><button class="btn dup" onclick="setStatus(\''+t.id+'\',\'Doublon\')" '+(locked?'disabled':'')+'>Doublon</button></div>';out+='</div>';return out;}
function render(){let c=counts();let list=byCountry(currentCountry);let out='';out+='<div class="top"><h1>Validation Traditions UE — 2 traditions par pays</h1></div><div class="wrap">';out+='<div class="summary"><div class="sum">Traditions<br>'+TRADITIONS.length+'</div><div class="sum">OK<br>'+c.OK+'</div><div class="sum">À reformuler<br>'+c['À reformuler']+'</div><div class="sum">À remplacer<br>'+c['À remplacer']+'</div><div class="sum">Doublons<br>'+c.Doublon+'</div></div>';out+='<div class="grid"><div class="side"><h2>Pays UE</h2>';COUNTRIES.forEach(function(country){out+='<button class="country '+(country===currentCountry?'active ':'')+countryStatus(country)+'" onclick="selectCountry(\''+country+'\')">'+(locks[country]?'🔒 ':'')+html(country)+'<br><small>'+byCountry(country).map(function(t){return t.name;}).join(' · ')+'</small></button>';});out+='<div class="actions"><button class="btn ghost" onclick="exportJSON()">Exporter JSON</button><button class="btn ghost" onclick="copyCSV()">Copier CSV</button><button class="btn replace" onclick="resetAll()">Reset local</button></div></div>';out+='<div class="main"><h2>'+html(currentCountry)+'</h2><span class="pill">2 traditions</span><span class="pill">'+(locks[currentCountry]?'Pays verrouillé':'Pays modifiable')+'</span><div class="progress"><div class="bar" style="width:'+progressCountry(currentCountry)+'%"></div></div><div class="actions"><button class="btn ok" onclick="validateCountry()">Valider/verrouiller ce pays</button><button class="btn ghost" onclick="unlockCountry()">Déverrouiller</button><button class="btn nav" onclick="nextCountry()">Pays suivant</button></div>';list.forEach(function(t){out+=renderTrad(t);});out+='<div id="export"></div></div></div></div>';app.innerHTML=out;}
function saveVisibleComments(){byCountry(currentCountry).forEach(function(t){let el=document.getElementById('comment_'+t.id);if(el){reviews[t.id]=Object.assign({status:statusOf(t)},reviews[t.id]||{},{comment:el.value});}});save();}
function selectCountry(c){saveVisibleComments();currentCountry=c;save();render();}
function setStatus(id,status){let t=TRADITIONS.find(function(x){return x.id===id;});let el=document.getElementById('comment_'+id);reviews[id]={status:status,comment:el?el.value:'',name:t?t.name:'',country:t?t.country:''};save();render();}
function validateCountry(){saveVisibleComments();byCountry(currentCountry).forEach(function(t){if(!reviews[t.id])reviews[t.id]={status:'OK',comment:''};if(reviews[t.id].status==='À valider')reviews[t.id].status='OK';});locks[currentCountry]=true;save();render();}
function unlockCountry(){delete locks[currentCountry];save();render();}
function nextCountry(){let i=COUNTRIES.indexOf(currentCountry);selectCountry(COUNTRIES[(i+1)%COUNTRIES.length]);}
function exportJSON(){saveVisibleComments();document.getElementById('export').innerHTML='<h3>Export JSON</h3><pre>'+html(JSON.stringify({reviews:reviews,locks:locks},null,2))+'</pre>';}
function copyCSV(){saveVisibleComments();let rows=[['Tradition_ID','Country','Tradition','Theme','Status','Locked','Comment','Question','Correct']];TRADITIONS.forEach(function(t){let r=reviews[t.id]||{status:'À valider',comment:''};rows.push([t.id,t.country,t.name,t.theme,r.status,locks[t.country]?'YES':'NO',r.comment||'',t.question,t.correct]);});let csv=rows.map(function(r){return r.map(function(v){return '"'+String(v).replaceAll('"','""')+'"';}).join(';');}).join('\n');if(navigator.clipboard)navigator.clipboard.writeText(csv);document.getElementById('export').innerHTML='<h3>CSV copié / à copier</h3><pre>'+html(csv)+'</pre>';}
function resetAll(){if(confirm('Effacer toute la validation locale ?')){localStorage.removeItem('trad_eu_v3_reviews');localStorage.removeItem('trad_eu_v3_locks');localStorage.removeItem('trad_eu_v3_country');reviews={};locks={};currentCountry=COUNTRIES[0];render();}}
render();
