let currentSubject=localStorage.getItem('trad_v2_subject') || SUBJECTS[0].id;
let reviews=JSON.parse(localStorage.getItem('trad_v2_reviews') || '{}');
let locks=JSON.parse(localStorage.getItem('trad_v2_locks') || '{}');
const app=document.getElementById('app');
function bySubject(id){return QUESTIONS.filter(q=>q.subjectId===id)}
function subjectStatus(id){let arr=bySubject(id); if(locks[id]) return 'done'; let statuses=arr.map(q=>(reviews[q.id]||{}).status||'À valider'); if(statuses.some(s=>s==='À remplacer'||s==='Doublon')) return 'problem'; if(statuses.some(s=>s==='À reformuler')) return 'review'; if(statuses.every(s=>s==='OK')) return 'done'; return '';}
function counts(){let c={OK:0,'À reformuler':0,'À remplacer':0,Doublon:0,'À valider':0}; QUESTIONS.forEach(q=>{let s=(reviews[q.id]||{}).status||'À valider'; c[s]=(c[s]||0)+1}); return c}
function render(){let c=counts(); let subj=SUBJECTS.find(s=>s.id===currentSubject); let rows=bySubject(currentSubject); app.innerHTML=`<div class="top"><h1>Validation V2 — Quiz Traditions par sujet</h1></div><div class="wrap"><div class="summary"><div class="sum">Questions<br>${QUESTIONS.length}</div><div class="sum">OK<br>${c.OK}</div><div class="sum">À reformuler<br>${c['À reformuler']}</div><div class="sum">À remplacer<br>${c['À remplacer']}</div><div class="sum">Doublons<br>${c.Doublon}</div></div><div class="grid"><div class="side"><h2>Sujets</h2>${SUBJECTS.map(s=>`<button class="subject ${s.id===currentSubject?'active':''} ${subjectStatus(s.id)}" onclick="selectSubject('${s.id}')">${locks[s.id]?'🔒 ':''}${s.name}<br><small>${s.id}</small></button>`).join('')}<div class="actions"><button class="btn ghost" onclick="exportJSON()">Exporter JSON</button><button class="btn ghost" onclick="copyCSV()">Copier CSV</button><button class="btn replace" onclick="resetAll()">Reset local</button></div></div><div class="main"><h2>${subj.name}</h2><span class="pill">${subj.id}</span><span class="pill">${rows.length} questions</span><span class="pill">${locks[subj.id]?'Sujet verrouillé':'Sujet modifiable'}</span><div class="progress"><div class="bar" style="width:${progressSubject(subj.id)}%"></div></div><div class="actions"><button class="btn ok" onclick="validateSubject()">Valider/verrouiller le sujet</button><button class="btn ghost" onclick="unlockSubject()">Déverrouiller</button><button class="btn nav" onclick="nextSubject()">Sujet suivant</button></div>${rows.map(renderQuestion).join('')}<div id="export"></div></div></div></div>`}
function renderQuestion(q){let r=reviews[q.id]||{status:'À valider',comment:''};let locked=locks[q.subjectId];return `<div class="qcard ${locked?'locked':''}"><div class="qhead"><span class="pill">${q.id}</span><span class="pill">${q.type}</span><span class="pill">Statut : ${r.status}</span></div><div class="question">${escapeHtml(q.question)}</div><div class="answers">${q.answers.map((a,idx)=>`<div class="answer ${a===q.correct?'correct':''}">${String.fromCharCode(65+idx)}. ${escapeHtml(a)}</div>`).join('')}</div><div class="explanation"><strong>Bonne réponse :</strong> ${escapeHtml(q.correct)}<br><br><strong>Explication :</strong> ${escapeHtml(q.explanation)}</div><h4>Commentaire</h4><textarea class="comment" id="comment_${q.id}" ${locked?'disabled':''}>${escapeHtml(r.comment||'')}</textarea><div class="actions"><button class="btn ok" onclick="setStatus('${q.id}','OK')" ${locked?'disabled':''}>OK</button><button class="btn rewrite" onclick="setStatus('${q.id}','À reformuler')" ${locked?'disabled':''}>À reformuler</button><button class="btn replace" onclick="setStatus('${q.id}','À remplacer')" ${locked?'disabled':''}>À remplacer</button><button class="btn dup" onclick="setStatus('${q.id}','Doublon')" ${locked?'disabled':''}>Doublon</button></div></div>`}
function escapeHtml(s){return String(s||'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]))}
function selectSubject(id){saveVisibleComments(); currentSubject=id; localStorage.setItem('trad_v2_subject',id); render()}
function saveVisibleComments(){bySubject(currentSubject).forEach(q=>{let el=document.getElementById('comment_'+q.id); if(el){reviews[q.id]={...(reviews[q.id]||{status:'À valider'}),comment:el.value}}}); localStorage.setItem('trad_v2_reviews',JSON.stringify(reviews))}
function setStatus(id,status){let el=document.getElementById('comment_'+id); reviews[id]={status,comment:el?el.value:'',question:(QUESTIONS.find(q=>q.id===id)||{}).question}; localStorage.setItem('trad_v2_reviews',JSON.stringify(reviews)); render()}
function progressSubject(id){let arr=bySubject(id); let done=arr.filter(q=>((reviews[q.id]||{}).status||'À valider')!=='À valider').length; return Math.round(done/arr.length*100)}
function validateSubject(){saveVisibleComments(); bySubject(currentSubject).forEach(q=>{if(!reviews[q.id]) reviews[q.id]={status:'OK',comment:''}; if(reviews[q.id].status==='À valider') reviews[q.id].status='OK'}); locks[currentSubject]=true; persist(); render()}
function unlockSubject(){delete locks[currentSubject]; persist(); render()}
function nextSubject(){let idx=SUBJECTS.findIndex(s=>s.id===currentSubject); selectSubject(SUBJECTS[(idx+1)%SUBJECTS.length].id)}
function persist(){localStorage.setItem('trad_v2_reviews',JSON.stringify(reviews)); localStorage.setItem('trad_v2_locks',JSON.stringify(locks))}
function exportJSON(){saveVisibleComments(); document.getElementById('export').innerHTML=`<h3>Export JSON</h3><pre>${escapeHtml(JSON.stringify({reviews,locks},null,2))}</pre>`}
function copyCSV(){saveVisibleComments(); let rows=[['Question_ID','Subject_ID','Subject','Type','Status','Locked','Comment','Question','Correct']]; QUESTIONS.forEach(q=>{let r=reviews[q.id]||{status:'À valider',comment:''}; rows.push([q.id,q.subjectId,q.subject,q.type,r.status,locks[q.subjectId]?'YES':'NO',r.comment||'',q.question,q.correct])}); let csv=rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(';')).join('\n'); if(navigator.clipboard) navigator.clipboard.writeText(csv); document.getElementById('export').innerHTML='<h3>CSV copié / à copier</h3><pre>'+escapeHtml(csv)+'</pre>'}
function resetAll(){if(confirm('Effacer toute la validation locale ?')){localStorage.removeItem('trad_v2_reviews');localStorage.removeItem('trad_v2_locks');localStorage.removeItem('trad_v2_subject');reviews={};locks={};currentSubject=SUBJECTS[0].id;render()}}
render();